ServerRoot "/usr/local/apache2"
Listen 80

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule unixd_module modules/mod_unixd.so

LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule headers_module modules/mod_headers.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule log_config_module modules/mod_log_config.so

User daemon
Group daemon

ServerName dev.local.com

<VirtualHost *:80>
    ServerAlias *.localhost

    ProxyPreserveHost On

    RewriteEngine On
    RewriteCond %{HTTP_HOST} ^([^.]+)\.([^.]+)\.localhost$ [NC]
    RewriteRule ^/(.*)$ \
        http://host.docker.internal:5001/cluster/proxy/%1/%2/$1 \
        [P,L]

    ProxyPassReverse / http://host.docker.internal:5001/cluster/proxy/

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
