import os

NAME="app"
VERSION="1.0"
PACKAGE_MANAGER="npm"
DEBUG=True
PORT="5002"
HOST="0.0.0.0"
PYTHONDONTWRITEBYTECODE=""
CWD=os.path.dirname(os.path.abspath(__file__))
STATIC_SITE=False
TYPESCRIPT=True
TAILWIND=True
LOG_LEVEL="DEBUG"
UVICORN_WORKERS="1"

GOOGLE_CLIENT_ID="REDACTED_GOOGLE_CLIENT_ID"
GOOGLE_CLIENT_SECRET="REDACTED_GOOGLE_CLIENT_SECRET"
GOOGLE_REDIRECT_URI="http://localhost:5002/api/v1/auth/callback"
JWT_SECRET="REDACTED_JWT_SECRET"
SESSION_TTL=86400

# Optional: Redis configuration
# REDIS_URL="redis://localhost:6379/0"

# Optional: Docker configuration
# DOCKER_MAX_IMAGE_AGE_HOURS = "24"
# DOCKER_BUILD_TIMEOUT_SECONDS = "600"
# DOCKER_MAX_CONCURRENT_BUILDS = "5"