"""empty message

Revision ID: 0057fe8d6cb8
Revises: 7823c2b78fbc
Create Date: 2026-01-26 16:58:07.980823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0057fe8d6cb8'
down_revision: Union[str, Sequence[str], None] = '7823c2b78fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k8spod', sa.Column('service_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('k8spod', sa.Column('automount_service_account_token', sa.Boolean(), nullable=True))
    op.add_column('k8spod', sa.Column('host_network', sa.Boolean(), nullable=True))
    op.add_column('k8spod', sa.Column('dns_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('k8spod', sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('k8spod', sa.Column('subdomain', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('k8spod', sa.Column('termination_grace_period_seconds', sa.Integer(), nullable=True))
    op.add_column('k8spod', sa.Column('enable_service_links', sa.Boolean(), nullable=True))
    op.add_column('k8spod', sa.Column('share_process_namespace', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('k8spod', 'share_process_namespace')
    op.drop_column('k8spod', 'enable_service_links')
    op.drop_column('k8spod', 'termination_grace_period_seconds')
    op.drop_column('k8spod', 'subdomain')
    op.drop_column('k8spod', 'hostname')
    op.drop_column('k8spod', 'dns_policy')
    op.drop_column('k8spod', 'host_network')
    op.drop_column('k8spod', 'automount_service_account_token')
    op.drop_column('k8spod', 'service_account_name')
    # ### end Alembic commands ###
