"""empty message

Revision ID: 021ee1a1291b
Revises: dedebe74f237
Create Date: 2026-02-01 17:24:03.914544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '021ee1a1291b'
down_revision: Union[str, Sequence[str], None] = 'dedebe74f237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codesourcecontrol', sa.Column('registry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'codesourcecontrol', 'registryconfig', ['registry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'codesourcecontrol', type_='foreignkey')
    op.drop_column('codesourcecontrol', 'registry_id')
    # ### end Alembic commands ###
