"""empty message

Revision ID: 088863751edd
Revises: 08d4e04cd75f
Create Date: 2026-06-15 16:41:38.502486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '088863751edd'
down_revision: Union[str, Sequence[str], None] = '08d4e04cd75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_instances', schema=None) as batch_op:
        batch_op.drop_column('error_message')

    # ### end Alembic commands ###
