"""empty message

Revision ID: 132d7b277599
Revises: 021ee1a1291b
Create Date: 2026-03-09 18:09:16.884540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '132d7b277599'
down_revision: Union[str, Sequence[str], None] = '021ee1a1291b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k8shttproutemetadataprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8shttprouteparentrefsprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8shttprouterulesprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8shttproute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_profile_id', sa.Integer(), nullable=True),
    sa.Column('rules_profile_id', sa.Integer(), nullable=True),
    sa.Column('parent_refs_profile_id', sa.Integer(), nullable=True),
    sa.Column('hostnames', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dynamic_attr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['metadata_profile_id'], ['k8shttproutemetadataprofile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_refs_profile_id'], ['k8shttprouteparentrefsprofile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rules_profile_id'], ['k8shttprouterulesprofile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('k8shttproute')
    op.drop_table('k8shttprouterulesprofile')
    op.drop_table('k8shttprouteparentrefsprofile')
    op.drop_table('k8shttproutemetadataprofile')
    # ### end Alembic commands ###
