"""empty message

Revision ID: 1fd60a0dc7a0
Revises: 99693f5a1930
Create Date: 2026-01-27 00:59:36.129288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1fd60a0dc7a0'
down_revision: Union[str, Sequence[str], None] = '99693f5a1930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentconfig', sa.Column('replicas', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentconfig', 'replicas')
    # ### end Alembic commands ###
