"""empty message

Revision ID: 266f869bb46c
Revises: dede78ab849e
Create Date: 2026-01-27 00:35:59.063045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '266f869bb46c'
down_revision: Union[str, Sequence[str], None] = 'dede78ab849e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentconfig', sa.Column('required_source_control', sa.BOOLEAN(), nullable=True))
    op.add_column('deploymentconfig', sa.Column('source_control_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('deploymentconfig', sa.Column('derived_deployment_id', sa.INTEGER(), nullable=True))
    op.alter_column('deploymentconfig', 'code_source_control_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deploymentconfig', 'code_source_control_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('deploymentconfig', 'derived_deployment_id')
    op.drop_column('deploymentconfig', 'source_control_branch')
    op.drop_column('deploymentconfig', 'required_source_control')
    # ### end Alembic commands ###
