"""empty message

Revision ID: 3ba269e92921
Revises: 132d7b277599
Create Date: 2026-03-09 18:18:54.626612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ba269e92921'
down_revision: Union[str, Sequence[str], None] = '132d7b277599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k8shttproutehostnamesprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('k8shttproute', sa.Column('hostnames_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'k8shttproute', 'k8shttproutehostnamesprofile', ['hostnames_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'k8shttproute', type_='foreignkey')
    op.drop_column('k8shttproute', 'hostnames_profile_id')
    op.drop_table('k8shttproutehostnamesprofile')
    # ### end Alembic commands ###
