"""empty message

Revision ID: 3ed288fc3e5e
Revises: 497fe55875a1
Create Date: 2026-04-14 01:50:56.231301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ed288fc3e5e'
down_revision: Union[str, Sequence[str], None] = '497fe55875a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # NOTE: The credentials table was manually migrated from 'githubpat' to 'integrationcredential' 
    # outside of Alembic to preserve data and support multi-provider tokens.
    # Skipping redundant table create/drop to avoid conflicts.
    
    # op.create_table('integrationcredential', ...) # Already exists
    # op.drop_table('githubpat') # Already renamed
    
    # Update foreign key on codesourcecontrol
    try:
        op.drop_constraint('codesourcecontrol_pat_id_fkey', 'codesourcecontrol', type_='foreignkey')
    except Exception:
        pass
    op.create_foreign_key('codesourcecontrol_credential_id_fkey', 'codesourcecontrol', 'integrationcredential', ['pat_id'], ['id'])
    
    # Add library release columns to deploymentconfig
    op.add_column('deploymentconfig', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='kubernetes'))
    op.add_column('deploymentconfig', sa.Column('package_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('deploymentconfig', sa.Column('release_strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('deploymentconfig', sa.Column('package_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentconfig', 'package_name')
    op.drop_column('deploymentconfig', 'release_strategy')
    op.drop_column('deploymentconfig', 'package_type')
    op.drop_column('deploymentconfig', 'category')
    op.drop_constraint(None, 'codesourcecontrol', type_='foreignkey')
    op.create_foreign_key(op.f('codesourcecontrol_pat_id_fkey'), 'codesourcecontrol', 'githubpat', ['pat_id'], ['id'])
    op.create_table('githubpat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token_encrypted', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('scopes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('githubpat_pkey'))
    )
    op.drop_table('integrationcredential')
    # ### end Alembic commands ###
