"""Refactor Service to Multi-Entity

Revision ID: 419fc98d20f5
Revises: 64e84714b299
Create Date: 2026-01-27 10:20:16.376497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '419fc98d20f5'
down_revision: Union[str, Sequence[str], None] = '64e84714b299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k8sservicemetadataprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8sserviceprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8sserviceselectorprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8sservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_profile_id', sa.Integer(), nullable=True),
    sa.Column('metadata_profile_id', sa.Integer(), nullable=True),
    sa.Column('selector_profile_id', sa.Integer(), nullable=True),
    sa.Column('dynamic_attr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['metadata_profile_id'], ['k8sservicemetadataprofile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selector_profile_id'], ['k8sserviceselectorprofile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_profile_id'], ['k8sserviceprofile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('k8sservicespec')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k8sservicespec',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('namespace', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meta_data_profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('selector_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dynamic_attr', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('clusterIP', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ipFamilyPolicy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sessionAffinity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('internalTrafficPolicy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('externalTrafficPolicy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('publishNotReadyAddresses', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('loadBalancerIP', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('healthCheckNodePort', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('allocateLoadBalancerNodePorts', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('loadBalancerClass', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('externalName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meta_data_profile_id'], ['k8spodmetadataprofile.id'], name=op.f('k8sservicespec_meta_data_profile_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selector_id'], ['k8sdeploymentselectorprofile.id'], name=op.f('k8sservicespec_selector_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('k8sservicespec_pkey'))
    )
    op.drop_table('k8sservice')
    op.drop_table('k8sserviceselectorprofile')
    op.drop_table('k8sserviceprofile')
    op.drop_table('k8sservicemetadataprofile')
    # ### end Alembic commands ###
