"""empty message

Revision ID: 497fe55875a1
Revises: b4f20146787f
Create Date: 2026-04-13 23:34:13.669714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '497fe55875a1'
down_revision: Union[str, Sequence[str], None] = 'b4f20146787f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keydeployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('linux_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('privilege_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_error', sa.TEXT(), nullable=True),
    sa.Column('restrictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system_managed', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['sshkey.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keydeployment_key_id'), 'keydeployment', ['key_id'], unique=False)
    op.create_index(op.f('ix_keydeployment_linux_username'), 'keydeployment', ['linux_username'], unique=False)
    op.create_index(op.f('ix_keydeployment_system_id'), 'keydeployment', ['system_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keydeployment_system_id'), table_name='keydeployment')
    op.drop_index(op.f('ix_keydeployment_linux_username'), table_name='keydeployment')
    op.drop_index(op.f('ix_keydeployment_key_id'), table_name='keydeployment')
    op.drop_table('keydeployment')
    # ### end Alembic commands ###
