"""empty message

Revision ID: 4c7441be427f
Revises: 94e6224e34d8
Create Date: 2026-01-27 00:57:37.927483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c7441be427f'
down_revision: Union[str, Sequence[str], None] = '94e6224e34d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentconfig', 'annotations')
    op.drop_column('deploymentconfig', 'profiles')
    op.drop_column('deploymentconfig', 'replicas')
    op.drop_column('deploymentconfig', 'labels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentconfig', sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('deploymentconfig', sa.Column('replicas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deploymentconfig', sa.Column('profiles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('deploymentconfig', sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
