"""empty message

Revision ID: 4e4aa70cbfba
Revises: ba61f783c09a
Create Date: 2026-01-05 23:33:59.384201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e4aa70cbfba'
down_revision: Union[str, Sequence[str], None] = 'ba61f783c09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('githubprstate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('githubprstate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('repo_full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pr_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_comment_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_triggered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('githubprstate_pkey'))
    )
    # ### end Alembic commands ###
