"""empty message

Revision ID: 5457e071f621
Revises: 9a4c319cd38a
Create Date: 2026-01-27 01:46:28.118680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5457e071f621'
down_revision: Union[str, Sequence[str], None] = '9a4c319cd38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentconfig', 'labels')
    op.drop_column('deploymentconfig', 'annotations')
    op.drop_column('deploymentconfig', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentconfig', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('deploymentconfig', sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('deploymentconfig', sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
