"""empty message

Revision ID: 56992034bd9d
Revises: 8d38e5cb8c90
Create Date: 2026-04-14 20:08:48.025929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56992034bd9d'
down_revision: Union[str, Sequence[str], None] = '8d38e5cb8c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentconfig', sa.Column('registry_credential_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentconfig', 'registry_credential_id')
    # ### end Alembic commands ###
