"""empty message

Revision ID: 5ce477e809cb
Revises: 9268046c403e
Create Date: 2026-03-29 18:47:52.956566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ce477e809cb'
down_revision: Union[str, Sequence[str], None] = '9268046c403e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codesourcecontrol', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codesourcecontrol', 'status')
    # ### end Alembic commands ###
