"""empty message

Revision ID: 63ec8279a102
Revises: 5457e071f621
Create Date: 2026-01-27 02:05:53.907872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63ec8279a102'
down_revision: Union[str, Sequence[str], None] = '5457e071f621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentrun', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('deploymentrun', 'image_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentrun', sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('deploymentrun', 'images')
    # ### end Alembic commands ###
