"""empty message

Revision ID: 643cd2152c0d
Revises: a123222eee48
Create Date: 2026-04-17 10:48:13.065008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '643cd2152c0d'
down_revision: Union[str, Sequence[str], None] = 'a123222eee48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addonplugin', sa.Column('service_port', sa.Integer(), nullable=False, server_default='80'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addonplugin', 'service_port')
    # ### end Alembic commands ###
