"""Add K8sServiceSpec table

Revision ID: 64e84714b299
Revises: 3cf4b474b641
Create Date: 2026-01-27 10:09:03.972947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64e84714b299'
down_revision: Union[str, Sequence[str], None] = '3cf4b474b641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k8sservicespec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_data_profile_id', sa.Integer(), nullable=True),
    sa.Column('selector_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dynamic_attr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clusterIP', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ipFamilyPolicy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sessionAffinity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('internalTrafficPolicy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('externalTrafficPolicy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publishNotReadyAddresses', sa.Boolean(), nullable=True),
    sa.Column('loadBalancerIP', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('healthCheckNodePort', sa.Integer(), nullable=True),
    sa.Column('allocateLoadBalancerNodePorts', sa.Boolean(), nullable=True),
    sa.Column('loadBalancerClass', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('externalName', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['meta_data_profile_id'], ['k8spodmetadataprofile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selector_id'], ['k8sdeploymentselectorprofile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('k8sservicespec')
    # ### end Alembic commands ###
