"""empty message

Revision ID: 682dd37e7b24
Revises: 3ed288fc3e5e
Create Date: 2026-04-14 01:53:27.638707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '682dd37e7b24'
down_revision: Union[str, Sequence[str], None] = '3ed288fc3e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integrationcredential', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'github'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integrationcredential', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'github'::character varying"))
    # ### end Alembic commands ###
