"""empty message

Revision ID: 6b1279285406
Revises: 25081de24668
Create Date: 2026-01-27 11:50:50.836750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b1279285406'
down_revision: Union[str, Sequence[str], None] = '25081de24668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('k8sservice_service_profile_id_fkey'), 'k8sservice', type_='foreignkey')
    op.drop_column('k8sservice', 'service_profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k8sservice', sa.Column('service_profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('k8sservice_service_profile_id_fkey'), 'k8sservice', 'k8sserviceprofile', ['service_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
