"""empty message

Revision ID: 6cd43bafe004
Revises: 56992034bd9d
Create Date: 2026-04-15 00:27:17.814117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6cd43bafe004'
down_revision: Union[str, Sequence[str], None] = '56992034bd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kubeconfig_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('kubeconfig_cluster', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kubeconfig_audit')
    # ### end Alembic commands ###
