"""empty message

Revision ID: 6cf2ada2ad51
Revises: 
Create Date: 2026-01-24 23:49:04.254027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cf2ada2ad51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deploymentconfigvolume')
    op.drop_table('deploymentconfigcontainer')
    op.add_column('deploymentconfig', sa.Column('profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('deploymentconfig_deployment_strategy_id_fkey'), 'deploymentconfig', type_='foreignkey')
    op.drop_column('deploymentconfig', 'scheduling_profile_id')
    op.drop_column('deploymentconfig', 'deployment_strategy_id')
    op.drop_column('deploymentconfig', 'service_ports')
    op.add_column('k8scontainerprofile', sa.Column('profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('k8scontainerprofile', 'container_name')
    op.drop_column('k8scontainerprofile', 'readiness_probe_id')
    op.drop_column('k8scontainerprofile', 'liveness_probe_id')
    op.drop_column('k8scontainerprofile', 'lifecycle_profile_id')
    op.drop_column('k8scontainerprofile', 'security_context')
    op.drop_column('k8scontainerprofile', 'resources_profile_id')
    op.drop_column('k8scontainerprofile', 'volume_mounts')
    op.drop_column('k8scontainerprofile', 'startup_probe_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k8scontainerprofile', sa.Column('startup_probe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('k8scontainerprofile', sa.Column('volume_mounts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('k8scontainerprofile', sa.Column('resources_profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('k8scontainerprofile', sa.Column('security_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('k8scontainerprofile', sa.Column('lifecycle_profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('k8scontainerprofile', sa.Column('liveness_probe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('k8scontainerprofile', sa.Column('readiness_probe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('k8scontainerprofile', sa.Column('container_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('k8scontainerprofile', 'profiles')
    op.add_column('deploymentconfig', sa.Column('service_ports', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('deploymentconfig', sa.Column('deployment_strategy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deploymentconfig', sa.Column('scheduling_profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('deploymentconfig_deployment_strategy_id_fkey'), 'deploymentconfig', 'deploymentstrategy', ['deployment_strategy_id'], ['id'])
    op.drop_column('deploymentconfig', 'profiles')
    op.create_table('deploymentconfigcontainer',
    sa.Column('deployment_config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('container_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['container_profile_id'], ['k8scontainerprofile.id'], name=op.f('deploymentconfigcontainer_container_profile_id_fkey')),
    sa.ForeignKeyConstraint(['deployment_config_id'], ['deploymentconfig.id'], name=op.f('deploymentconfigcontainer_deployment_config_id_fkey')),
    sa.PrimaryKeyConstraint('deployment_config_id', 'container_profile_id', name=op.f('deploymentconfigcontainer_pkey'))
    )
    op.create_table('deploymentconfigvolume',
    sa.Column('deployment_config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('volume_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deployment_config_id'], ['deploymentconfig.id'], name=op.f('deploymentconfigvolume_deployment_config_id_fkey')),
    sa.PrimaryKeyConstraint('deployment_config_id', 'volume_profile_id', name=op.f('deploymentconfigvolume_pkey'))
    )
    # ### end Alembic commands ###
