"""empty message

Revision ID: 700fb3cead2e
Revises: 266f869bb46c
Create Date: 2026-01-27 00:46:40.110147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '700fb3cead2e'
down_revision: Union[str, Sequence[str], None] = '266f869bb46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentconfig', sa.Column('deployment_strategy_id', sa.INTEGER(), nullable=True))
    op.alter_column('deploymentconfig', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deploymentconfig', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('deploymentconfig', 'deployment_strategy_id')
    # ### end Alembic commands ###
