"""empty message

Revision ID: 758a7184d923
Revises: 088863751edd
Create Date: 2026-06-15 16:45:30.564232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '758a7184d923'
down_revision: Union[str, Sequence[str], None] = '088863751edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('external_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('cloud_created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_instances', schema=None) as batch_op:
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('cloud_created_at')
        batch_op.drop_column('state')
        batch_op.drop_column('external_ip')
        batch_op.drop_column('internal_ip')

    # ### end Alembic commands ###
