"""empty message

Revision ID: 77b0e6452028
Revises: 0057fe8d6cb8
Create Date: 2026-01-26 19:49:55.888662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77b0e6452028'
down_revision: Union[str, Sequence[str], None] = '0057fe8d6cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k8scontainerprofile', sa.Column('tty', sa.Boolean(), nullable=True))
    op.add_column('k8scontainerprofile', sa.Column('stdin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('k8scontainerprofile', 'stdin')
    op.drop_column('k8scontainerprofile', 'tty')
    # ### end Alembic commands ###
