"""empty message

Revision ID: 7823c2b78fbc
Revises: 6cf2ada2ad51
Create Date: 2026-01-26 10:17:04.583136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7823c2b78fbc'
down_revision: Union[str, Sequence[str], None] = '6cf2ada2ad51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k8scontainerprofile', sa.Column('dynamic_attr', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('k8scontainerprofile', 'ports')
    op.drop_column('k8scontainerprofile', 'profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k8scontainerprofile', sa.Column('profiles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('k8scontainerprofile', sa.Column('ports', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('k8scontainerprofile', 'dynamic_attr')
    # ### end Alembic commands ###
