"""empty message

Revision ID: 793ae7e3f212
Revises: 880e6df05a54
Create Date: 2025-06-24 20:35:36.470163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '793ae7e3f212'
down_revision: Union[str, Sequence[str], None] = '880e6df05a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentconfig', sa.Column('soft_delete', sa.Boolean(), default=False))
    op.add_column('deploymentconfig', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('deploymentconfig', sa.Column('hard_delete', sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentconfig', 'hard_delete')
    op.drop_column('deploymentconfig', 'deleted_at')
    op.drop_column('deploymentconfig', 'soft_delete')
    # ### end Alembic commands ###
