"""empty message

Revision ID: 7c79042b7e8b
Revises: e537607499b7
Create Date: 2026-03-29 13:32:20.214622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c79042b7e8b'
down_revision: Union[str, Sequence[str], None] = 'e537607499b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dockerconfig', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dockerconfig', 'is_active')
    # ### end Alembic commands ###
