"""empty message

Revision ID: 7d00774a2cb1
Revises: 
Create Date: 2026-05-07 17:20:28.350743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d00774a2cb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addonplugin',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('helm_repo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('helm_repo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('helm_chart_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('helm_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_port', sa.Integer(), nullable=False),
    sa.Column('default_values', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proxy_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('features', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addonplugin_name'), 'addonplugin', ['name'], unique=True)
    op.create_table('deploymentstrategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dockerconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_cert', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ca_cert', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verify', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('soft_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('deleted_at', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=True)
    op.create_table('integrationcredential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8scontainerprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_pull_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('command', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('working_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tty', sa.Boolean(), nullable=True),
    sa.Column('stdin', sa.Boolean(), nullable=True),
    sa.Column('dynamic_attr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8sdeploymentprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8sdeploymentselectorprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8sentityprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8shttproutehostnamesprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8shttproutemetadataprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8shttprouteparentrefsprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8shttprouterulesprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8spodmetadataprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8spodprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8sservicemetadataprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8sserviceprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8sserviceselectorprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kubeconfig_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('kubeconfig_cluster', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kubeconfig_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_rules', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registryconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registryconfig_name'), 'registryconfig', ['name'], unique=True)
    op.create_table('service_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_setting_key'), 'service_setting', ['key'], unique=True)
    op.create_table('sourcecodebuild',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_name_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pull_request_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pr_head_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_branch_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('time_taken', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sourcecodebuildlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('logs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sshkey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_key', sa.TEXT(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sshkey_name'), 'sshkey', ['name'], unique=False)
    op.create_index(op.f('ix_sshkey_user_id'), 'sshkey', ['user_id'], unique=False)
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('private_key', sa.TEXT(), nullable=True),
    sa.Column('os_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_key_deployed', sa.BOOLEAN(), nullable=True),
    sa.Column('default_key_id', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_name'), 'system', ['name'], unique=True)
    op.create_table('codesourcecontrol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pat_id', sa.Integer(), nullable=True),
    sa.Column('registry_id', sa.Integer(), nullable=True),
    sa.Column('docker_config_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('polling_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['docker_config_id'], ['dockerconfig.id'], ),
    sa.ForeignKeyConstraint(['pat_id'], ['integrationcredential.id'], ),
    sa.ForeignKeyConstraint(['registry_id'], ['registryconfig.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('k8shttproute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_profile_id', sa.Integer(), nullable=True),
    sa.Column('rules_profile_id', sa.Integer(), nullable=True),
    sa.Column('parent_refs_profile_id', sa.Integer(), nullable=True),
    sa.Column('hostnames_profile_id', sa.Integer(), nullable=True),
    sa.Column('hostnames', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dynamic_attr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['hostnames_profile_id'], ['k8shttproutehostnamesprofile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metadata_profile_id'], ['k8shttproutemetadataprofile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_refs_profile_id'], ['k8shttprouteparentrefsprofile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rules_profile_id'], ['k8shttprouterulesprofile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8spod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('automount_service_account_token', sa.Boolean(), nullable=True),
    sa.Column('host_network', sa.Boolean(), nullable=True),
    sa.Column('dns_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subdomain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('termination_grace_period_seconds', sa.Integer(), nullable=True),
    sa.Column('enable_service_links', sa.Boolean(), nullable=True),
    sa.Column('share_process_namespace', sa.Boolean(), nullable=True),
    sa.Column('metadata_profile_id', sa.Integer(), nullable=True),
    sa.Column('containers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dynamic_attr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['metadata_profile_id'], ['k8spodmetadataprofile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8sservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_profile_id', sa.Integer(), nullable=True),
    sa.Column('selector_profile_id', sa.Integer(), nullable=True),
    sa.Column('dynamic_attr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cluster_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_family_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_affinity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('internal_traffic_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_traffic_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publish_not_ready_addresses', sa.Boolean(), nullable=True),
    sa.Column('load_balancer_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('health_check_node_port', sa.Integer(), nullable=True),
    sa.Column('allocate_load_balancer_node_ports', sa.Boolean(), nullable=True),
    sa.Column('load_balancer_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['metadata_profile_id'], ['k8sservicemetadataprofile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selector_profile_id'], ['k8sserviceselectorprofile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keydeployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('linux_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('privilege_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_error', sa.TEXT(), nullable=True),
    sa.Column('restrictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system_managed', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['sshkey.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keydeployment_key_id'), 'keydeployment', ['key_id'], unique=False)
    op.create_index(op.f('ix_keydeployment_linux_username'), 'keydeployment', ['linux_username'], unique=False)
    op.create_index(op.f('ix_keydeployment_system_id'), 'keydeployment', ['system_id'], unique=False)
    op.create_table('librarysetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_credential_id', sa.Integer(), nullable=True),
    sa.Column('repo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('repo_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auto_push', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['github_credential_id'], ['integrationcredential.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sshauditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keystroke_data', sa.TEXT(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sshauditlog_session_id'), 'sshauditlog', ['session_id'], unique=False)
    op.create_index(op.f('ix_sshauditlog_user_id'), 'sshauditlog', ['user_id'], unique=False)
    op.create_table('systemaccess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('access_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemaccess_user_id'), 'systemaccess', ['user_id'], unique=False)
    op.create_table('usergrouplink',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('codesourcecontrolbranch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_source_control_id', sa.Integer(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registry_id', sa.Integer(), nullable=True),
    sa.Column('docker_config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_source_control_id'], ['codesourcecontrol.id'], ),
    sa.ForeignKeyConstraint(['docker_config_id'], ['dockerconfig.id'], ),
    sa.ForeignKeyConstraint(['registry_id'], ['registryconfig.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deploymentconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deployment_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required_source_control', sa.BOOLEAN(), nullable=True),
    sa.Column('code_source_control_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_control_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('derived_deployment_id', sa.INTEGER(), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('deployment_strategy_id', sa.INTEGER(), nullable=True),
    sa.Column('http_route_id', sa.INTEGER(), nullable=True),
    sa.Column('chart_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('env_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('package_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('package_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registry_credential_id', sa.INTEGER(), nullable=True),
    sa.Column('soft_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('deleted_at', sa.DATE(), nullable=True),
    sa.Column('hard_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('replicas', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['code_source_control_name'], ['codesourcecontrol.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_name')
    )
    op.create_table('k8sdeployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=True),
    sa.Column('min_ready_seconds', sa.Integer(), nullable=True),
    sa.Column('revision_history_limit', sa.Integer(), nullable=True),
    sa.Column('progress_deadline_seconds', sa.Integer(), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=True),
    sa.Column('selector_id', sa.Integer(), nullable=True),
    sa.Column('pod_id', sa.Integer(), nullable=True),
    sa.Column('dynamic_attr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['k8spod.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selector_id'], ['k8sdeploymentselectorprofile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sshauditevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['sshauditlog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sshauditevent_created_at'), 'sshauditevent', ['created_at'], unique=False)
    op.create_index(op.f('ix_sshauditevent_log_id'), 'sshauditevent', ['log_id'], unique=False)
    op.create_table('deploymentrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jira', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deployment_config_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apply_derived_service', sa.BOOLEAN(), nullable=True),
    sa.Column('deployment_strategy_id', sa.Integer(), nullable=True),
    sa.Column('http_route_id', sa.Integer(), nullable=True),
    sa.Column('apply_derived_httproute', sa.BOOLEAN(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_config_id'], ['deploymentconfig.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deploymentrun')
    op.drop_index(op.f('ix_sshauditevent_log_id'), table_name='sshauditevent')
    op.drop_index(op.f('ix_sshauditevent_created_at'), table_name='sshauditevent')
    op.drop_table('sshauditevent')
    op.drop_table('k8sdeployment')
    op.drop_table('deploymentconfig')
    op.drop_table('codesourcecontrolbranch')
    op.drop_table('usergrouplink')
    op.drop_index(op.f('ix_systemaccess_user_id'), table_name='systemaccess')
    op.drop_table('systemaccess')
    op.drop_index(op.f('ix_sshauditlog_user_id'), table_name='sshauditlog')
    op.drop_index(op.f('ix_sshauditlog_session_id'), table_name='sshauditlog')
    op.drop_table('sshauditlog')
    op.drop_table('librarysetting')
    op.drop_index(op.f('ix_keydeployment_system_id'), table_name='keydeployment')
    op.drop_index(op.f('ix_keydeployment_linux_username'), table_name='keydeployment')
    op.drop_index(op.f('ix_keydeployment_key_id'), table_name='keydeployment')
    op.drop_table('keydeployment')
    op.drop_table('k8sservice')
    op.drop_table('k8spod')
    op.drop_table('k8shttproute')
    op.drop_table('codesourcecontrol')
    op.drop_index(op.f('ix_system_name'), table_name='system')
    op.drop_table('system')
    op.drop_index(op.f('ix_sshkey_user_id'), table_name='sshkey')
    op.drop_index(op.f('ix_sshkey_name'), table_name='sshkey')
    op.drop_table('sshkey')
    op.drop_table('sourcecodebuildlog')
    op.drop_table('sourcecodebuild')
    op.drop_index(op.f('ix_service_setting_key'), table_name='service_setting')
    op.drop_table('service_setting')
    op.drop_index(op.f('ix_registryconfig_name'), table_name='registryconfig')
    op.drop_table('registryconfig')
    op.drop_table('kubeconfig_audit')
    op.drop_table('k8sserviceselectorprofile')
    op.drop_table('k8sserviceprofile')
    op.drop_table('k8sservicemetadataprofile')
    op.drop_table('k8spodprofile')
    op.drop_table('k8spodmetadataprofile')
    op.drop_table('k8shttprouterulesprofile')
    op.drop_table('k8shttprouteparentrefsprofile')
    op.drop_table('k8shttproutemetadataprofile')
    op.drop_table('k8shttproutehostnamesprofile')
    op.drop_table('k8sentityprofile')
    op.drop_table('k8sdeploymentselectorprofile')
    op.drop_table('k8sdeploymentprofile')
    op.drop_table('k8scontainerprofile')
    op.drop_table('integrationcredential')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_table('group')
    op.drop_table('dockerconfig')
    op.drop_table('deploymentstrategy')
    op.drop_index(op.f('ix_addonplugin_name'), table_name='addonplugin')
    op.drop_table('addonplugin')
    # ### end Alembic commands ###
