"""empty message

Revision ID: 7e124d61905a
Revises: 836f538e9796
Create Date: 2025-06-25 00:03:22.845768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e124d61905a'
down_revision: Union[str, Sequence[str], None] = '836f538e9796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'deploymentconfig', ['deployment_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deploymentconfig', type_='unique')
    # ### end Alembic commands ###
