"""empty message

Revision ID: 7ff7dd712f19
Revises: c1a2b3d4e5f6
Create Date: 2026-04-16 17:34:39.997606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7ff7dd712f19'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addonplugin',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('helm_repo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('helm_repo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('helm_chart_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('helm_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_values', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proxy_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('features', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addonplugin_name'), 'addonplugin', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addonplugin_name'), table_name='addonplugin')
    op.drop_table('addonplugin')
    # ### end Alembic commands ###
