"""empty message

Revision ID: 875ebc99244a
Revises: 45582401d4e6
Create Date: 2026-01-27 02:33:59.606017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '875ebc99244a'
down_revision: Union[str, Sequence[str], None] = '45582401d4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentconfig', 'deployment_strategy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentconfig', sa.Column('deployment_strategy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
