"""empty message

Revision ID: 88163c809209
Revises: e41742fa2d67
Create Date: 2025-06-30 21:51:30.338995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88163c809209'
down_revision: Union[str, Sequence[str], None] = 'e41742fa2d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sourcecodebuild',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_name_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pull_request_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sourcecodebuildlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('logs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sourcecodebuildlog')
    op.drop_table('sourcecodebuild')
    # ### end Alembic commands ###
