"""empty message

Revision ID: 8d38e5cb8c90
Revises: ed25ff9bfaa0
Create Date: 2026-04-14 12:29:58.254728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d38e5cb8c90'
down_revision: Union[str, Sequence[str], None] = 'ed25ff9bfaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('codesourcecontrol', sa.Column('polling_enabled', sa.Boolean(), nullable=True))
    
    # Update existing rows to False
    op.execute("UPDATE codesourcecontrol SET polling_enabled = false")
    
    # Set to NOT NULL
    op.alter_column('codesourcecontrol', 'polling_enabled', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codesourcecontrol', 'polling_enabled')
    # ### end Alembic commands ###
