"""empty message

Revision ID: 9268046c403e
Revises: 7c79042b7e8b
Create Date: 2026-03-29 15:33:20.640285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9268046c403e'
down_revision: Union[str, Sequence[str], None] = '7c79042b7e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codesourcecontrol', sa.Column('docker_config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'codesourcecontrol', 'dockerconfig', ['docker_config_id'], ['id'])
    op.add_column('codesourcecontrolbranch', sa.Column('registry_id', sa.Integer(), nullable=True))
    op.add_column('codesourcecontrolbranch', sa.Column('docker_config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'codesourcecontrolbranch', 'registryconfig', ['registry_id'], ['id'])
    op.create_foreign_key(None, 'codesourcecontrolbranch', 'dockerconfig', ['docker_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'codesourcecontrolbranch', type_='foreignkey')
    op.drop_constraint(None, 'codesourcecontrolbranch', type_='foreignkey')
    op.drop_column('codesourcecontrolbranch', 'docker_config_id')
    op.drop_column('codesourcecontrolbranch', 'registry_id')
    op.drop_constraint(None, 'codesourcecontrol', type_='foreignkey')
    op.drop_column('codesourcecontrol', 'docker_config_id')
    # ### end Alembic commands ###
