"""empty message

Revision ID: 94760f8603e1
Revises: e5c39027f763
Create Date: 2025-07-07 14:02:06.087291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94760f8603e1'
down_revision: Union[str, Sequence[str], None] = 'e5c39027f763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentconfig', sa.Column('node_selector', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('deploymentconfig', sa.Column('tolerations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('deploymentconfig', sa.Column('affinity', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('deploymentconfig', sa.Column('volumes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentconfig', 'volumes')
    op.drop_column('deploymentconfig', 'affinity')
    op.drop_column('deploymentconfig', 'tolerations')
    op.drop_column('deploymentconfig', 'node_selector')
    # ### end Alembic commands ###
