"""empty message

Revision ID: a123222eee48
Revises: 4b6b2b122a45
Create Date: 2026-04-17 10:45:48.075667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a123222eee48'
down_revision: Union[str, Sequence[str], None] = '4b6b2b122a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addonplugin', 'service_port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addonplugin', sa.Column('service_port', sa.INTEGER(), server_default=sa.text('80'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
