"""empty message

Revision ID: b468e4f2c135
Revises: 17045dcd0381
Create Date: 2026-01-27 01:35:49.689832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b468e4f2c135'
down_revision: Union[str, Sequence[str], None] = '17045dcd0381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentconfig', sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('deploymentconfig', sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('deploymentconfig', sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentconfig', 'annotations')
    op.drop_column('deploymentconfig', 'labels')
    op.drop_column('deploymentconfig', 'tag')
    # ### end Alembic commands ###
