"""empty message

Revision ID: b4f20146787f
Revises: e66504c4df29
Create Date: 2026-04-12 21:31:05.912059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4f20146787f'
down_revision: Union[str, Sequence[str], None] = 'e66504c4df29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('private_key', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system', 'private_key')
    # ### end Alembic commands ###
