"""empty message

Revision ID: b90aa68a1ea4
Revises: d5d6ebd4a672
Create Date: 2026-01-28 09:10:56.830013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b90aa68a1ea4'
down_revision: Union[str, Sequence[str], None] = 'd5d6ebd4a672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k8sservice', sa.Column('cluster_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('k8sservice', sa.Column('ip_family_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('k8sservice', sa.Column('session_affinity', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('k8sservice', sa.Column('internal_traffic_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('k8sservice', sa.Column('external_traffic_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('k8sservice', sa.Column('publish_not_ready_addresses', sa.Boolean(), nullable=True))
    op.add_column('k8sservice', sa.Column('load_balancer_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('k8sservice', sa.Column('health_check_node_port', sa.Integer(), nullable=True))
    op.add_column('k8sservice', sa.Column('allocate_load_balancer_node_ports', sa.Boolean(), nullable=True))
    op.add_column('k8sservice', sa.Column('load_balancer_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('k8sservice', sa.Column('external_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('k8sservice', 'external_name')
    op.drop_column('k8sservice', 'load_balancer_class')
    op.drop_column('k8sservice', 'allocate_load_balancer_node_ports')
    op.drop_column('k8sservice', 'health_check_node_port')
    op.drop_column('k8sservice', 'load_balancer_ip')
    op.drop_column('k8sservice', 'publish_not_ready_addresses')
    op.drop_column('k8sservice', 'external_traffic_policy')
    op.drop_column('k8sservice', 'internal_traffic_policy')
    op.drop_column('k8sservice', 'session_affinity')
    op.drop_column('k8sservice', 'ip_family_policy')
    op.drop_column('k8sservice', 'cluster_ip')
    # ### end Alembic commands ###
