"""empty message

Revision ID: b9cb2a16247a
Revises: b90aa68a1ea4
Create Date: 2026-01-28 09:16:39.517256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9cb2a16247a'
down_revision: Union[str, Sequence[str], None] = 'b90aa68a1ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k8sservice', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('k8sservice', 'type')
    # ### end Alembic commands ###
