"""add compute_instances table

Revision ID: c052266403f2
Revises: 588616ea6aeb
Create Date: 2026-05-20 19:03:45.126076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c052266403f2'
down_revision: Union[str, Sequence[str], None] = '588616ea6aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('machine_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('boot_disk_size_gb', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('gcp_resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compute_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compute_instances_instance_name'), ['instance_name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compute_instances_instance_name'))

    op.drop_table('compute_instances')
    # ### end Alembic commands ###
