"""empty message

Revision ID: c4e7a93684ee
Revises: c052266403f2
Create Date: 2026-05-20 21:36:57.957922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4e7a93684ee'
down_revision: Union[str, Sequence[str], None] = 'c052266403f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_instances', schema=None) as batch_op:
        batch_op.drop_column('temporary_admin_password')

    # ### end Alembic commands ###
