"""empty message

Revision ID: c5c816519007
Revises: 92a226a8d779
Create Date: 2026-05-13 00:11:17.817807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5c816519007'
down_revision: Union[str, Sequence[str], None] = '92a226a8d779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubeconfigfile', sa.Column('is_system_config', sa.Boolean(), nullable=False))
    op.add_column('kubeconfigfile', sa.Column('system_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('kubeconfigfile', 'content_encrypted',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kubeconfigfile', 'content_encrypted',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('kubeconfigfile', 'system_path')
    op.drop_column('kubeconfigfile', 'is_system_config')
    # ### end Alembic commands ###
