"""empty message

Revision ID: d254598ca73a
Revises: 1fd60a0dc7a0
Create Date: 2026-01-27 01:07:36.388624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd254598ca73a'
down_revision: Union[str, Sequence[str], None] = '1fd60a0dc7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first
    op.add_column('deploymentconfig', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Step 2: Populate existing rows with default value 'active'
    op.execute("UPDATE deploymentconfig SET status = 'active' WHERE status IS NULL")
    
    # Step 3: Make column NOT NULL
    op.alter_column('deploymentconfig', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentconfig', 'status')
    # ### end Alembic commands ###
