"""empty message

Revision ID: d5d6ebd4a672
Revises: ff1d43ff1aea
Create Date: 2026-01-27 22:19:16.840313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5d6ebd4a672'
down_revision: Union[str, Sequence[str], None] = 'ff1d43ff1aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentrun', sa.Column('apply_derived_service', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentrun', 'apply_derived_service')
    # ### end Alembic commands ###
