"""empty message

Revision ID: d5d9bf0d43b5
Revises: 423e958a49cb
Create Date: 2026-01-27 09:32:08.626687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5d9bf0d43b5'
down_revision: Union[str, Sequence[str], None] = '423e958a49cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k8sdeployment', sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=sa.text("'Deployment'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('k8sdeployment', 'kind')
    # ### end Alembic commands ###
