"""empty message

Revision ID: dbfff245918e
Revises: 6cd43bafe004
Create Date: 2026-04-15 10:24:30.828996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbfff245918e'
down_revision: Union[str, Sequence[str], None] = '6cd43bafe004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First add the columns as nullable
    op.add_column('kubeconfig_audit', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('kubeconfig_audit', sa.Column('kubeconfig_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('kubeconfig_audit', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('kubeconfig_audit', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE kubeconfig_audit SET status = 'ready' WHERE status IS NULL")
    op.execute("UPDATE kubeconfig_audit SET retry_count = 0 WHERE retry_count IS NULL")
    
    # Then make them non-nullable
    op.alter_column('kubeconfig_audit', 'status', nullable=False)
    op.alter_column('kubeconfig_audit', 'retry_count', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kubeconfig_audit', 'error_message')
    op.drop_column('kubeconfig_audit', 'retry_count')
    op.drop_column('kubeconfig_audit', 'kubeconfig_encrypted')
    op.drop_column('kubeconfig_audit', 'status')
    # ### end Alembic commands ###
