"""empty message

Revision ID: dede78ab849e
Revises: 2bbf255e7b36
Create Date: 2026-01-26 23:40:50.940725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dede78ab849e'
down_revision: Union[str, Sequence[str], None] = '2bbf255e7b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codesourcecontrol', sa.Column('pat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'codesourcecontrol', 'githubpat', ['pat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'codesourcecontrol', type_='foreignkey')
    op.drop_column('codesourcecontrol', 'pat_id')
    # ### end Alembic commands ###
