"""empty message

Revision ID: e2d69ff1630e
Revises: 4f3a00f9dd2c
Create Date: 2026-04-08 18:57:10.944079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2d69ff1630e'
down_revision: Union[str, Sequence[str], None] = '4f3a00f9dd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=True)
    op.create_table('sshkey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_key', sa.TEXT(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sshkey_name'), 'sshkey', ['name'], unique=False)
    op.create_index(op.f('ix_sshkey_user_id'), 'sshkey', ['user_id'], unique=False)
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('os_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_name'), 'system', ['name'], unique=True)
    op.create_table('sshauditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keystroke_data', sa.TEXT(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sshauditlog_session_id'), 'sshauditlog', ['session_id'], unique=False)
    op.create_index(op.f('ix_sshauditlog_user_id'), 'sshauditlog', ['user_id'], unique=False)
    op.create_table('systemaccess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('access_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemaccess_user_id'), 'systemaccess', ['user_id'], unique=False)
    op.create_table('usergrouplink',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usergrouplink')
    op.drop_index(op.f('ix_systemaccess_user_id'), table_name='systemaccess')
    op.drop_table('systemaccess')
    op.drop_index(op.f('ix_sshauditlog_user_id'), table_name='sshauditlog')
    op.drop_index(op.f('ix_sshauditlog_session_id'), table_name='sshauditlog')
    op.drop_table('sshauditlog')
    op.drop_index(op.f('ix_system_name'), table_name='system')
    op.drop_table('system')
    op.drop_index(op.f('ix_sshkey_user_id'), table_name='sshkey')
    op.drop_index(op.f('ix_sshkey_name'), table_name='sshkey')
    op.drop_table('sshkey')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
