"""empty message

Revision ID: e537607499b7
Revises: b2c3d4e5f6a7
Create Date: 2026-03-12 18:28:11.791478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e537607499b7'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deploymentrun', 'apply_derived_service',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.BOOLEAN(),
               postgresql_using='apply_derived_service::text::boolean',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deploymentrun', 'apply_derived_service',
               existing_type=sa.BOOLEAN(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
