"""empty message

Revision ID: e5c39027f763
Revises: 0b6537569661
Create Date: 2025-07-04 21:33:18.268922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5c39027f763'
down_revision: Union[str, Sequence[str], None] = '0b6537569661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sourcecodebuild',
        'time_taken',
        type_=sa.Float(),
        postgresql_using="EXTRACT(EPOCH FROM time_taken)",
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sourcecodebuild', 'time_taken',
               existing_type=sa.Float(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
