"""empty message

Revision ID: e66504c4df29
Revises: 3854eb9cbbd5
Create Date: 2026-04-08 20:23:02.273921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e66504c4df29'
down_revision: Union[str, Sequence[str], None] = '3854eb9cbbd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_setting_key'), 'service_setting', ['key'], unique=True)
    op.add_column('system', sa.Column('service_key_deployed', sa.BOOLEAN(), nullable=True))
    op.add_column('system', sa.Column('default_key_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system', 'default_key_id')
    op.drop_column('system', 'service_key_deployed')
    op.drop_index(op.f('ix_service_setting_key'), table_name='service_setting')
    op.drop_table('service_setting')
    # ### end Alembic commands ###
