"""Add versioning fields to deployment run

Revision ID: e7dffe014dcd
Revises: 682dd37e7b24
Create Date: 2026-04-14 08:42:29.881508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7dffe014dcd'
down_revision: Union[str, Sequence[str], None] = '682dd37e7b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentrun', sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('deploymentrun', sa.Column('release_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('deploymentrun', sa.Column('is_public', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentrun', 'is_public')
    op.drop_column('deploymentrun', 'release_notes')
    op.drop_column('deploymentrun', 'version')
    # ### end Alembic commands ###
