"""empty message

Revision ID: fc8c5663d259
Revises: 88163c809209
Create Date: 2025-07-04 20:49:01.345307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc8c5663d259'
down_revision: Union[str, Sequence[str], None] = '88163c809209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentrun', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sourcecodebuild', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sourcecodebuild', sa.Column('time_taken', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sourcecodebuild', 'time_taken')
    op.drop_column('sourcecodebuild', 'created_at')
    op.drop_column('deploymentrun', 'created_at')
    # ### end Alembic commands ###
