"""add_service_id_to_deployment_config

Revision ID: ff1d43ff1aea
Revises: 6b1279285406
Create Date: 2026-01-27 20:14:56.539987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff1d43ff1aea'
down_revision: Union[str, Sequence[str], None] = '6b1279285406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentconfig', sa.Column('service_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentconfig', 'service_id')
    # ### end Alembic commands ###
