import React, { useEffect, useState } from "react";
import { StorageInfo } from "@/types/storage";
import { StoragesList } from "@/components/docker/storages/StoragesList";
import { CreateStorageForm } from "@/components/docker/storages/forms/CreateStorageForm";
import { HardDrive, Search } from "lucide-react";
import RouteDescription from "@/components/route-description";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { DefaultService } from '@/gingerJs_api_client';
import { VolumeActionRequest } from '@/gingerJs_api_client/models/VolumeActionRequest';

const fetchStorages = async () => {
  const response = await DefaultService.apiDockerStoragesGet();
  return (response as { storages: StorageInfo[] }).storages;
};

const deleteStorage = async (id: string): Promise<void> => {
  const request: VolumeActionRequest = {
    action: "remove",
    volume_id: id
  };
  await DefaultService.apiDockerStoragesPost({ requestBody: request });
};

const createStorage = async (data: any): Promise<void> => {
  // Transform the data to match the API's expected format
  const transformedData = {
    name: data.name,
    driver: data.driver,
    driverOpts: data.driver_opts || {}, // Convert driver_opts to driverOpts
    labels: data.labels || {}
  };

  const request: VolumeActionRequest = {
    action: "add",
    add_data: transformedData
  };
  await DefaultService.apiDockerStoragesPost({ requestBody: request });
};

export default function StoragePage() {
  const [storages, setStorages] = useState<StorageInfo[]>([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [showCreate, setShowCreate] = useState(false);

  const getStorages = async () => {
    const items = await fetchStorages();
    setStorages(items);
  };

  useEffect(() => {
    getStorages();
  }, []);

  const filteredStorages = storages.filter(
    (storage) =>
      storage.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleDelete = async (id: string) => {
    try {
      await deleteStorage(id);
      await getStorages();
      toast.success('Storage deleted successfully');
      return true;
    } catch (error) {
      console.error('Failed to delete storage:', error);
      toast.error('Failed to delete storage');
      return false;
    }
  };

  const handleCreateStorage = async (data: any) => {
    try {
      await createStorage(data);
      toast.success('Storage created successfully');
      await getStorages();
      setShowCreate(false);
    } catch (error) {
      console.error('Failed to create storage:', error);
      toast.error('Failed to create storage');
    }
  };

  return (
    <div className='w-full'>
      <div className="space-y-6">
        <RouteDescription
          title={
            <div className="flex items-center gap-2">
              <HardDrive className='h-4 w-4'/>
              <h2>Storages</h2>
            </div>
          }
          shortDescription='Manage Docker storage (volumes)—create, inspect, and remove volumes used for persistent data in containers.'
          description='Docker storages (volumes) provide persistent storage for containers. They are the preferred mechanism for persisting data generated by and used by Docker containers. Storages are completely managed by Docker and are independent of the container lifecycle.'
        />
        <Card className="p-4 rounded-[0.5rem] shadow-none bg-white border border-gray-200 min-h-[500px]">
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle className="text-lg">Your Volumes</CardTitle>
              <CardDescription>
                {storages.length} volumes found
              </CardDescription>
            </div>
            <Button onClick={() => setShowCreate(true)}>
              <HardDrive className="mr-2 h-4 w-4" />
              Create Volume
            </Button>
          </CardHeader>
          <CardContent className="p-0 shadow-none">
            <div className="relative px-6">
              <Search className="absolute left-9 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                type="search"
                placeholder="Search volumes..."
                className="w-full pl-9 bg-background"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
            <StoragesList 
              storages={filteredStorages} 
              onDelete={handleDelete}
            />
          </CardContent>
        </Card>
      </div>
      
      <Dialog open={showCreate} onOpenChange={setShowCreate}>
        <DialogContent className="max-w-none w-screen h-screen p-0">
        <DialogHeader className="py-4 px-6 border-b flex !flex-row items-center">
            <DialogTitle className="flex items-center gap-2 w-full px-6">
              <HardDrive className="h-5 w-5" />
              Create Volume
            </DialogTitle>
          </DialogHeader>
          <div className="flex-1 h-[calc(100vh-8rem)] px-6">
            <CreateStorageForm
              onSubmit={handleCreateStorage}
              onCancel={() => setShowCreate(false)}
            />
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
